name: CI

# Trigger CI for pull requests to the main branch or when a release is made
# Do not trigger CI for draft pull request
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:  
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  tests:
    name: C++ - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint on the source files
        run: |
          cd src
          cpplint *
          cd ..

      - name: Run cpplint on the unit test files
        run: |
          cd test/unit_tests/
          cpplint --filter=-'build/include' *
          cd ../..

      - name: Build the unit test
        run: |
          cmake -S . -B build
          cmake --build build --target unit_tests

      - name: Run the unit test
        run: ./build/test/unit_tests/unit_tests
